name: pet_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  graphql_flutter: ^5.1.2
  go_router: ^13.0.1
  flutter_riverpod: ^2.4.9
  animation_wrappers: ^3.0.0
  sizer_pro: ^2.2.0
  flutter_bounceable: ^1.1.0
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  flutter_localization: ^0.2.2
  easy_dynamic_theme: ^2.3.1
  flutter_svg: ^2.0.9
  haptic_feedback: ^0.5.1+1
  toastification: ^2.3.0

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/backs/
    - assets/icons/

  fonts:
    - family: Dongle
      fonts:
        - asset: assets/fonts/dongle/Dongle-Bold.ttf
        - asset: assets/fonts/dongle/Dongle-Light.ttf
        - asset: assets/fonts/dongle/Dongle-Regular.ttf
